#!/usr/bin/env php

<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require_once __DIR__.'/bootstrap/console.php';

$app->registerCommand('hello', function (array $argv) use ($app) {
    $name = isset ($argv[2]) ? $argv[2] : "World";
    $app->getFormatter()->display("Hello $name!!!");
});

$app->registerCommand('help', function (array $argv) use ($app) {
    $app->getFormatter()->display("usage: minicli hello [ your-name ]");
});

$app->runCommand($argv);

